"""What an anonymous caller may see on the public read-only feeds.

**The problem this fixes.** `/dashboard/overview` and `/agents/{name}` are public by design —
a judge, or anyone with the link, needs them to work without a login, and they carry no
credentials. But the payload they returned included `shift.records[]` (32 named staff with
their unit, trailing hours, and a fatigue risk level) and `hr.records[]` (named staff with
credential expiry dates and an "expired" status). That data is synthetic here, so nothing real
leaked — but the *shape* is an unauthenticated endpoint publishing per-employee fatigue and
credentialing records, which is exactly the HR data an enterprise policy fences, and it does
not survive being pointed at a real roster.

The project already reasoned carefully about leakage at field granularity — `project_approval`
keeps the manager's address and message bodies off these same feeds, and every payroll
projection was checked for `hourly_rate` before `hourly_rate` was added to the roster at all.
This module applies the same care at endpoint granularity.

**The design.** Redact rather than gate. Hard-401ing these routes would fix the exposure and
break the judge-accessible URL, so instead the anonymous view keeps every aggregate (which is
what the fleet story is actually told with — unit summaries, category counts, reorder
decisions, armor events) and drops the individual rows. The payload shape is preserved: a
redacted list is an empty list plus a sibling `_redacted` block giving the count and the
reason, so the dashboard can render "sign in to see staff-level detail" instead of an
ambiguous empty state.

Pure functions over plain dicts, no I/O — unit-tested alongside the other pure logic.
"""

from __future__ import annotations

from copy import deepcopy

# Why each of these is individually identifying, for the next person deciding whether to add a
# field to the public feed:
#   shift.records         — name + unit + trailing hours + fatigue risk, per employee
#   hr.records            — name + credential expiry + expired/expiring status, per employee
#   guest_doctor_hours    — name + unit + hours worked, per per-diem clinician
_REDACTED_PATHS: tuple[tuple[str, ...], ...] = (
    ("shift", "records"),
    ("hr", "records"),
    ("guest_doctor_hours",),
)

_REASON = "Staff-level detail requires a signed-in manager session."

# Free-text fields on `autonomous_actions` that an agent wrote. These are the subtle leak:
# emptying the structured staff lists above does nothing about an agent's own prose, and
# Shift's instruction explicitly tells it to "name the staff member, their unit, and the
# specific action". A live run produced "4 staff members in the ICU ... Nurse IC-01", straight
# onto the public feed. `summary` is generated by services/triggers.py from aggregates only
# ("ICU critical-fatigue staff rose from 0 to 4"), never from a roster row, so it stays — which
# is why the feed still reads correctly signed out.
_AGENT_PROSE_FIELDS = ("response", "prompt")

# Approval task types whose `recipient_label` names a person rather than a company. The vendor
# ones stay visible on purpose: "contacting MedSupply Primary" is the whole point of the panel
# and a supplier's trading name is not personal data. "Nurse IC-01 (ICU)" is.
_STAFF_DIRECTED_TASKS = frozenset(
    {"notify_staff_reallocation", "notify_staff_credential_escalation"}
)
_WITHHELD_RECIPIENT = "A staff member"

# The subject line names the person too — "Shift reallocation: Per-Diem Nurse IC-00 to ICU on
# 2026-08-24". Redacting `recipient_label` and leaving `subject` would have been a fix that
# looked complete and wasn't.
_GENERIC_SUBJECT = {
    "notify_staff_reallocation": "Shift reallocation for a staff member",
    "notify_staff_credential_escalation": "Credential escalation for a staff member",
}

# Chaos what-if results embed the roster rows the projection was computed over. The rest of a
# result (unit, additional_patients, surge_days, items_needing_reorder, the reorder verdict) is
# aggregate and is what the replay panel actually renders, so only these two keys are dropped —
# each replaced by a count so the panel can still say how many people were involved.
_CHAOS_STAFF_KEYS = ("staffing_projection", "staff_needing_escalation")


def _redact_at(payload: dict, path: tuple[str, ...]) -> None:
    """Empties one list in place and annotates its parent with a `_redacted` marker."""
    *parents, leaf = path
    node = payload
    for key in parents:
        node = node.get(key)
        if not isinstance(node, dict):
            return
    original = node.get(leaf)
    if not isinstance(original, list):
        return
    node[leaf] = []
    node.setdefault("_redacted", {})[leaf] = {
        "withheld_count": len(original),
        "reason": _REASON,
    }


def _redact_agent_prose(payload: dict) -> None:
    """Strips an agent's own free text off `autonomous_actions`, in place."""
    actions = payload.get("autonomous_actions")
    if not isinstance(actions, list):
        return
    for action in actions:
        if not isinstance(action, dict):
            continue
        withheld = [field for field in _AGENT_PROSE_FIELDS if action.get(field)]
        for field in withheld:
            action[field] = ""
        if withheld:
            action["_redacted"] = {"fields": withheld, "reason": _REASON}


def _redact_recipient_labels(payload: dict) -> None:
    """Genericises staff-directed approval recipients and subjects, in place."""
    approvals = payload.get("approvals")
    if not isinstance(approvals, list):
        return
    for approval in approvals:
        if not isinstance(approval, dict):
            continue
        task_type = approval.get("task_type")
        if task_type in _STAFF_DIRECTED_TASKS:
            approval["recipient_label"] = _WITHHELD_RECIPIENT
            approval["subject"] = _GENERIC_SUBJECT.get(task_type, "Action for a staff member")


def _redact_chaos_results(payload: dict) -> None:
    """Drops the per-staff rows out of chaos what-if results, in place."""
    experiments = payload.get("chaos_experiments")
    if not isinstance(experiments, list):
        return
    for experiment in experiments:
        if not isinstance(experiment, dict):
            continue
        result = experiment.get("result")
        if not isinstance(result, dict):
            continue
        for key in _CHAOS_STAFF_KEYS:
            rows = result.get(key)
            if isinstance(rows, list) and rows:
                result[key] = []
                result.setdefault("_redacted", {})[key] = {
                    "withheld_count": len(rows),
                    "reason": _REASON,
                }


def redact_overview(payload: dict, *, authenticated: bool) -> dict:
    """Returns the payload an authenticated manager sees, or its redacted public counterpart.

    Deep-copies before mutating: `build_overview()`'s result is assembled fresh per request
    today, but a future cache in front of it would otherwise be permanently redacted by the
    first anonymous caller — a bug that would be invisible until a signed-in manager saw
    empty panels.
    """
    if authenticated:
        return payload
    redacted = deepcopy(payload)
    for path in _REDACTED_PATHS:
        _redact_at(redacted, path)
    _redact_agent_prose(redacted)
    _redact_recipient_labels(redacted)
    _redact_chaos_results(redacted)
    redacted["_public_view"] = True
    return redacted


def redact_agent_detail(payload: dict, *, authenticated: bool) -> dict:
    """Per-agent detail page equivalent. The agent payload nests each specialist's live state
    under `live_state`, so the same paths apply one level down; anything else it carries
    (activity log summaries, projected approvals, registry metadata) is already public-safe.
    """
    if authenticated:
        return payload
    redacted = deepcopy(payload)
    live_state = redacted.get("live_state")
    if isinstance(live_state, dict):
        for path in _REDACTED_PATHS:
            _redact_at(live_state, path)
        # The chaos agent's live_state *is* its experiment list, so the same treatment has to
        # reach one level down as well as at the top.
        _redact_chaos_results(live_state)
    _redact_agent_prose(redacted)
    _redact_recipient_labels(redacted)
    _redact_chaos_results(redacted)
    redacted["_public_view"] = True
    return redacted
